### ISSUE TITLE
Media Chooser seems to be broken

### ISSUE THREAD

**Issue by dkowis** [krille-chan/fluffychat#1963]
### Bug Description

On my Android phone, I can use the media picture to select an image from the gallery app, but it doesn't.... do anything. 

I cannot use it to select an image to upload for custom emoji, or to send to a room.

I can select a "file" to attach and send to a room, and if that file happens to be an image, it works as expected.

I can paste an image into the chat and have an image send. Will include screenshots

### Steps to Reproduce

1. try to add an image using the gallery app
2. pick the image
3. tap done
4. .... nothing happens.

### Expected Behavior

I should be able to pick an image for a custom emoji, or for sending into a channel.

### App Version

1.27.0 android

### Additional Platform Information

Android Samsung ZFold 4

**Comment by dkowis** [comment]
Step 1: 
![Image](https://github.com/user-attachments/assets/dcfeac84-5365-407f-b406-01ff6e4e03ca)

Step 2:
![Image](https://github.com/user-attachments/assets/49c2c6aa-a41e-421e-b6e1-94e4518ef2e6)

Step 3:
![Image](https://github.com/user-attachments/assets/36455fa0-b820-4667-aa93-6ff36eab41da)

Step 4: I'm just back at the room, as if I didn't do anything, no messages sent, nothing.

Same thing happens with the custom emoji picker, I can't ever create any custom emoji, because it doesn't do anything.

**Comment by williamkray** [comment]
confirmed on my unihertz tank mini, stock android 13, with fluffychat v1.127.0 from f-droid repo.

**Comment by JAicewizard** [comment]
Could this also affect not being able to set a pfp? I am in a room where someone mentioned not being able to set one and it reminded me of this.

**Comment by dkowis** [comment]
> Could this also affect not being able to set a pfp? I am in a room where someone mentioned not being able to set one and it reminded me of this.

If it's using a gallery picker, probably.

**Comment by krille-chan** [comment]
@dkowis thank you so much. Good thing is I have a device from the same vendor. In my case Z Flip 4. Maybe the problem is caused by a Flutter bug whic his now fixed in the latest hotfix. Can you try the beta version from the PlayStore?

**Comment by dkowis** [comment]
It did not fix it. I'm on 2.0.0 now.

The behavior is different, but still very broke.

the gallery picker shows up, and I tap on the image I want, then it goes to the regular gallery view, and still nothing happens on fluffychat.

Step one:
![Image](https://github.com/user-attachments/assets/c9528a40-7a9a-4c6b-a7ae-8077670bff17)

After picking an image:
![Image](https://github.com/user-attachments/assets/be061b06-39e7-4efc-b480-399ab2590fb1)

**Comment by krille-chan** [comment]
Hmm, sorry to hear that. This is then probably an edge case bug with the https://pub.dev/packages/image_picker package

**Comment by JAicewizard** [comment]
Are you able to reproduce the issue? I am on lineageOS. If you cannot reproduce I can try and fix this once im less busy (hopefully next week, but I have a lot of issues assigned to me already haha)

**Comment by dnchshrp** [comment]
same issue for me on moto g84, stock android 14
neither Ente, Fossify Gallery or even google photos work with FluffyChat :<

**Comment by JAicewizard** [comment]
This seems to be fixed in the real 2.0.0 release, I no longer have any issues. I discovered this when trying to debug this not working, and it worked :D

Last week it didn't work, and I can't seem to find anything in the changelog to indicate a fix, but I guess it's probably a random combination of things??

**Comment by dkowis** [comment]
Yep, can confirm it's magically working now! Must've been a combination of things. Others can re-open if it still shows up for them.
