### ISSUE TITLE
[BUG]: Error Widget (matrix.to link)

### ISSUE THREAD

**Issue by LFd3v** [krille-chan/fluffychat#813]
- Operating system: linux
- Version: 1.17.1

### Exception
Null check operator used on a null value

### StackTrace
#0      PublicRoomBottomSheet.build (package:fluffychat/widgets/public_room_bottom_sheet.dart:85)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:5541)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)

(automatic report)

The error happened when trying to open a link to a room in the chat, something like https://matrix.to/#/#test:envs.net. A pop over is shown, with an orange box with a black X (like something is missing, please see attached image), but FluffyChat does not crash. 

I think this may be important because there is no other way to join a room using an alias in FluffyChat anymore.

<details><summary>ScreenShot</summary>

![Screenshot from 2024-01-16 21-15-41](https://github.com/krille-chan/fluffychat/assets/146497073/30743382-b46a-498d-9b8a-1795fdd04ca9)

</details>

**Comment by krille-chan** [comment]
Fixed in latest commit

**Comment by LFd3v** [comment]
@krille-chan I have installed v1.71.2 on Linux and the problem improved (a bit) but it is not fixed:

```
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: [Matrix] Something went wrong:  - Provider<MatrixState> not found for PublicRoomBottomSheet
```

![image](https://github.com/krille-chan/fluffychat/assets/146497073/70c40b2b-4228-49b8-b090-efd9dd691716)

I cannot reopen this issue, should I open a new one?

**Comment by LFd3v** [comment]
It seems that it is working fine as of v1.17.3. Thank you.
